package text

const (
	SaveOperatorMetricName       = "risk-rules.save_operator"
	SaveConditionsMetricName     = "risk-rules.save_conditions"
	SaveModuleMetricName         = "risk-rules.save_module"
	EvaluateChargeMetricName     = "risk-rules.charge_evaluation"
	SaveFieldMetricName          = "risk-rules.save_field"
	SaveListMetricName           = "risk-rules.save_list"
	UpdateListMetricName         = "risk-rules.update_list"
	DeleteListMetricName         = "risk-rules.delete_list"
	SaveRuleMetricName           = "risk-rules.save_rule"
	UpdateRuleMetricName         = "risk-rules.update_rule"
	DeleteRuleMetricName         = "risk-rules.delete_rule"
	UpdateModuleMetricName       = "risk-rules.update_module"
	DeleteModuleMetricName       = "risk-rules.delete_module"
	UpdateConditionMetricName    = "risk-rules.update_condition"
	DeleteConditionMetricName    = "risk-rules.delete_condition"
	DeleteOperatorMetricName     = "risk-rules.delete_operator"
	UpdateOperatorMetricName     = "risk-rules.update_operator"
	DeleteFieldMetricName        = "risk-rules.delete_field"
	UpdateFieldMetricName        = "risk-rules.update_field"
	SaveChargebackMetricName     = "risk-rules.save_chargeback"
	UpdateChargebackMetricName   = "risk-rules.update_chargeback"
	SaveMerchantsScoreMetricName = "risk-rules.save_merchants_score"

	MetricTagSuccess                 = "success:%t"
	MetricTagScope                   = "scope:%s"
	MetricTagTestRulesChangeDecision = "test_rules_change:%t"
	MetricTagRulesDecision           = "rules_decision:%s"
	MetricTagTestRulesDecision       = "test_rules_decision:%s"
	MetricTagCompany                 = "company:%s"
	MetricPaymentNetwork             = "Payment_network:%s"
	MetricCardType                   = "card_type:%s"
	MetricCountry                    = "country:%s"
	MetricIssuer                     = "issuer:%s"
	MetricStatus                     = "status:%s"

	LogTagMethod    = "Method"
	CompanyID       = "company_id"
	ListID          = "list_id"
	ListType        = "list_type:%s"
	ListDuplicated  = "list_duplicated:%t"
	List            = "list"
	Functionality   = "functionality"
	FamilyID        = "family_id"
	FamilyCompanyID = "family_company_id"
	ModuleID        = "module_id"
	Family          = "family"
	Chargeback      = "chargeback"
	ChargebackID    = "chargeback_id"
	Payer           = "payer"
	PayerID         = "payer_id"
	Email           = "email"
	MerchantScore   = "merchant_score"
)
