version: "3.3"
services:
  httpserver:
    image: risk-rules
    depends_on:
      - mongo
      - mockserver
    environment:
      WAIT_HOSTS: mongo:27018
      MONGODB_URI: mongodb://mongo:27018
      IS_OMNISCORE_ENABLED: true
      OMNISCORE_HOST: http://mockserver:3000
      INTERNAL_SERVICE_HOST: http://mockserver:3000
      S3_BUCKET: risk-bucket-stg
      ENV: test
    volumes:
      - ".:/go/src/risk-rules"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: rules
    command: mongod --port 27018 --setParameter ttlMonitorSleepSecs=1

  mockserver:
    image: mockoon/cli:latest
    command: "-d data  -p 3000"
    environment:
      d: data
    volumes:
      - ./files/mockserver.json:/data:ro
